name: pnml_ood_detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38ha312104_0
  - chardet=4.0.0=py38h578d9bd_1
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.2.89=h8f6ccaa_8
  - docopt=0.6.2=py_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuv=1.41.0=h7f98852_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.2.0=py38hc5bc63f_1
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - pandas=1.2.3=py38h51da96c_0
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pipreqs=0.4.10=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.0=h357f687_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.35.3=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - torchaudio=0.8.1=py38
  - torchvision=0.9.1=py38_cu102
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yarg=0.1.9=py_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - async-timeout==3.0.1
    - attrs==20.3.0
    - cachetools==4.2.1
    - cycler==0.10.0
    - fsspec==0.8.7
    - future==0.18.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.36.1
    - hydra-core==1.0.6
    - importlib-resources==5.1.2
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.1
    - multidict==5.1.0
    - oauthlib==3.1.0
    - omegaconf==2.0.6
    - ood-metrics==0.2.9
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pytorch-lightning==1.2.6
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.6.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==2.1.0
    - torchmetrics==0.2.0
    - tqdm==4.59.0
    - werkzeug==1.0.1
    - yarl==1.6.3
prefix: /home/ubuntu/anaconda3/envs/pnml_ood_detection
